### ISSUE TITLE
Script engine not displayed

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Orchard-Scripting-Extensions#2]
**henryfelipe** created on May 30, 2013: 
https://orchardscriptingext.codeplex.com/workitem/3

Hello. I have installed your module but when I will create a new script the "script engine" combobox does not show anyone option to select. 

What could be wrong? 

Thanks, 

Henry Felipe

**Comment by I3undy** [comment]
**henryfelipe** commented on May 31, 2013: 

Ok. I found that I need to install the extensions that I need, i.e., .Net extension.

But when I try to write a new script on Admin screen, I don't know where to write. Where scripts files are located? How to call editor to write a new script?

Thanks,

Henry Felipe

**Comment by I3undy** [comment]
@Piedone commented on May 31, 2013:

Thanks for your interest! This is not a bug but rather an issue with the documentation: this module doesn't contain a concrete scripting engine itself. You have to install one or more of those:
[PHP](https://github.com/Lombiq/Orchard-Scripting-Extensions-PHP)
[.NET(C#/VB)](https://github.com/Lombiq/Orchard-Scripting-Extensions-DotNet)
[JavaScript](https://github.com/Lombiq/Orchard-Scripting-Extensions-JavaScript)

**Comment by I3undy** [comment]
@Piedone commented on May 31, 2013:

*\* Closed by Piedone 05/30/2013 3:13PM

**Comment by I3undy** [comment]
@Piedone commented on May 31, 2013:

Please refer to "Script content types" and "Testbed" in the docs.

**Comment by I3undy** [comment]
**henryfelipe** commented on May 31, 2013:

Hi Piedone. 

Thanks a lot for your response, but I had read all documentation and sounds me so simple install and put it in operation. But I can't see where to write a new script. There is a script content type on my installation but doesn't show any field or space where to write my script code. Could be something wrong on my installation? I don't believe. 

In testbed the only one way to test is clicking on button "copy sample to editor" and execute it. But there is no space or field to put some code. 

Thanks. 

Henry Felipe

**Comment by I3undy** [comment]
@Piedone commented on May 31, 2013:

You should be able to see a code editor textbox under both a Script content item's editor and the testbed. If you can't see it then likely there's some JS issue, please check in Firebug or some other JS debugging tool whether there are any errors. Also if you're using Orchard 1.6 there's a bug regarding static resources that sometimes causes resources to get mixed up, thus JS errors to surface. A restart usually solves this.

**Comment by I3undy** [comment]
**henryfelipe** commented on May 31, 2013:

Thanks for your reply, Piedone.

I'll verify under firebug if there is any error and let you know about result.

Regards,

Henry Felipe

**Comment by I3undy** [comment]
@Piedone commented on Nov 20, 2013:

Could you verify if the issue still persists?

**Comment by I3undy** [comment]
@Piedone commented on  Jul 14, 2014:

Could you please verify?

**Comment by Piedone** [comment]
Assuming fixed.
