### ISSUE TITLE
Orchard 1.9.2 supported?

### ISSUE THREAD

**Issue by kerray** [Lombiq/Orchard-Scripting-Extensions#4]
Hi,
I've installed and enabled this module together with all required modules on Orchard 1.9.2, there are no errors in log, yet there is no sign of Scripting Testbed in the Admin menu, nor are there any scripting content types... When I try to add a breakpoint in AdminMenu.cs GetNavigation, it doesn't step in. Yet there are no errors or information in log with full logging enabled...

Thanks!

**Comment by Piedone** [comment]
Hi,

all this indicates that the modules weren't even loaded. Did you save them under correctly named folders, so e.g. this module is in Orchard.Web/Modules/OrchardHUN.Scripting? Also, use the version from the dev branch for 1.9.2.

**Comment by kerray** [comment]
Renaming the directory helped a bit, thanks for that. I'm pretty new to Orchard and didn't realize just downloading and copying the repository and might not be enough, when I've seen it in Modules and succesfully enabled it.

I'm now using https://github.com/Lombiq/Orchard-Scripting-Extensions/commit/472b6eda0fae663497968ee32e308521dd8f5711 but there are still some issues: 
1) there was `Modules\OrchardHUN.Scripting\Controllers\AdminController.cs(72): error CS1501: No overload for method 'NewPage' takes 2 arguments"` which I 'solved' by removing the second argument

2) but now I'm stuck on `System.Web.HttpCompileException (0x80004005): \Modules\OrchardHUN.Scripting\Handlers\PageHandler.cs(15): error CS1061: 'Orchard.ContentManagement.IContent' does not contain a definition for 'Weld' and no extension method 'Weld' accepting a first argument of type 'Orchard.ContentManagement.IContent' could be found (are you missing a using directive or an assembly reference?)` and any help would be appreciated

Thanks!

**Comment by Piedone** [comment]
Keep in mind that the module has dependencies as defined in the manifest: https://github.com/Lombiq/Orchard-Scripting-Extensions/blob/dev/Module.txt You'll need to also install those as elaborated in the Readme.

**Comment by kerray** [comment]
Those dependencies are all installed and enabled - Orchard wouldn't let me enable the module if they weren't. What directory should the Ace editor reside in? Currently it's in Orchard-Ace-Editor, simply cloned from GitHub, and I can't find any further info as to how else should I name it.

I also checked the readme and it mentions scripting engines, and I also have C# Scripting service installed and enabled.

I'll investigate further tomorrow.

Thanks for your time.

**Comment by Piedone** [comment]
Then it's probably the same issue: all extensions should be in a folder that has the same name as their project file, so Orchard-Ace-Editor isn't correct.

**Comment by kerray** [comment]
OK, thanks. The main problem probably was that some of the modules were downloaded from Orchard Gallery - I replaced them with current GitHub versions, updated references etc., and now I at least got the Scripting menu in Admin, and although the Testbed page is still empty, I think I'll be able to solve that.

Thanks for your help.

**Comment by Piedone** [comment]
OK, great!
